source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'HTNChallenge' do
    pod 'Alamofire', '~> 4.3'
    pod 'SwiftyJSON', '~> 3.1'
    pod 'Kingfisher', '~> 3.3'
    pod 'M13Checkbox', '~> 3.1.3'
end
